Repository utPLSQL/utPLSQL, pull requests merged in 2018-03, with the labels that each got.

#596 Cobertura Coverage Reporter
  docs/userguide/coverage.md
  source/create_synonyms_and_grants_for_public.sql
  source/create_synonyms_and_grants_for_user.sql
  source/install.sql
  source/reporters/ut_coverage_cobertura_reporter.tpb
  source/reporters/ut_coverage_cobertura_reporter.tps
  source/uninstall.sql
  test/core/reporters/test_coverage/test_cov_cobertura_reporter.pkb
  test/core/reporters/test_coverage/test_cov_cobertura_reporter.pks
  test/install_and_run_tests.sh
  test/install_tests.sql
Labels: enhancement

#591 Add Diff functionality to cursors, collections and object types
  docs/userguide/advanced_data_comparison.md
  docs/userguide/expectations.md
  source/core/ut_utils.pkb
  source/create_synonyms_and_grants_for_public.sql
  source/create_synonyms_and_grants_for_user.sql
  source/expectations/data_values/ut_compound_data_diff_tmp.sql
  source/expectations/data_values/ut_compound_data_helper.pkb
  source/expectations/data_values/ut_compound_data_helper.pks
  source/expectations/data_values/ut_compound_data_tmp.sql
  source/expectations/data_values/ut_compound_data_value.tpb
  source/expectations/data_values/ut_compound_data_value.tps
  source/expectations/data_values/ut_data_value.tpb
  source/expectations/data_values/ut_data_value.tps
  source/expectations/data_values/ut_data_value_anydata.tpb
  source/expectations/data_values/ut_data_value_anydata.tps
  source/expectations/data_values/ut_data_value_collection.tpb
  source/expectations/data_values/ut_data_value_collection.tps
  source/expectations/data_values/ut_data_value_object.tpb
  source/expectations/data_values/ut_data_value_object.tps
  source/expectations/data_values/ut_data_value_refcursor.tpb
  source/expectations/data_values/ut_data_value_refcursor.tps
  source/expectations/matchers/ut_equal.tpb
  source/expectations/matchers/ut_equal.tps
  source/expectations/matchers/ut_have_count.tpb
  source/install.sql
  source/uninstall.sql
  test/core/expectations/compound_data/test_expectation_anydata.pkb
  test/core/expectations/compound_data/test_expectation_anydata.pks
  test/core/expectations/compound_data/test_expectations_cursor.pkb
  test/core/expectations/compound_data/test_expectations_cursor.pks
Labels: enhancement, in progress

#608 Fixed `ORA-02055` issue.
  .travis/install.sh
  source/api/ut_runner.pkb
  test/api/test_ut_runner.pkb
  test/api/test_ut_runner.pks
Labels: bugfix

#607 File mapping is now unique for individual object.
  source/core/types/ut_file_mapping.tpb
Labels: bugfix

#605 State invalidation no longer stops utPLSQL from running
  .travis/install.sh
  source/api/ut.pkb
  source/api/ut_runner.pkb
  source/core/types/ut_executable.tpb
  source/core/ut_expectation_processor.pkb
  source/core/ut_expectation_processor.pks
  test/api/test_ut_run.pkb
  test/api/test_ut_run.pks
  test/install_tests.sql
Labels: enhancement

#619 New reporter for Microsoft Team Fundation Server (TFS)
  docs/images/tfs_details.png
  docs/images/tfs_summary.png
  docs/userguide/reporters.md
  source/create_synonyms_and_grants_for_public.sql
  source/create_synonyms_and_grants_for_user.sql
  source/install.sql
  source/reporters/ut_tfs_junit_reporter.tpb
  source/reporters/ut_tfs_junit_reporter.tps
  source/uninstall.sql
  test/api/test_ut_runner.pkb
  test/core/reporters/test_tfs_junit_reporter.pkb
  test/core/reporters/test_tfs_junit_reporter.pks
  test/install_tests.sql
Labels: enhancement
