Repository utPLSQL/utPLSQL, pull requests merged in 2018-11, with the labels that each got.

#773 Fix/join by grant
  source/expectations/data_values/ut_compound_data_helper.pkb
  source/expectations/data_values/ut_compound_data_helper.pks
  source/expectations/data_values/ut_compound_data_value.tpb
  test/install__min_usr_tests.sql
  test/install_and_run_tests.sh
  test/min_grant_user/min_grant_user_exp.pkb
  test/min_grant_user/min_grant_user_exp.pks
Labels: bugfix

#790 Updated documentation to include infrmation about reports encoding.
  docs/userguide/reporters.md
  docs/userguide/running-unit-tests.md
Labels: documentation, enhancement

#791 Added description fo timestamp bind-variable comparison in cursor.
  docs/userguide/expectations.md
Labels: documentation, enhancement

#789 Feature/force manual rollback option
  docs/userguide/running-unit-tests.md
  source/api/ut.pkb
  source/api/ut.pks
  source/api/ut_runner.pkb
  source/api/ut_runner.pks
  source/core/types/ut_logical_suite.tpb
  source/core/types/ut_logical_suite.tps
  source/core/types/ut_run.tpb
  source/core/types/ut_run.tps
  source/core/types/ut_suite_item.tpb
  source/core/types/ut_suite_item.tps
  test/api/test_ut_run.pkb
  test/api/test_ut_run.pks
Labels: enhancement

#797 Removed unneeded `sed` from test-runner
  .travis/get_project_build_version.sh
  .travis/get_project_version.sh
  test/install_and_run_tests.sh
Labels: enhancement
