Repository utPLSQL/utPLSQL, pull requests merged in 2018-04, with the labels that each got.

#628 Fixed issue when user executing tests doesn't have access to DBA_TYPES view
  source/api/ut_runner.pkb
  source/create_synonyms_and_grants_for_public.sql
  source/create_synonyms_and_grants_for_user.sql
Labels: in progress

#630 Fixes to file mapping and coverage documentation
  docs/images/coverage_html_details.png
  docs/images/coverage_html_summary.png
  docs/images/example_1_coverage_mapping.png
  docs/images/example_1_test_mapping.png
  docs/images/example_2_coverage_mapping.png
  docs/images/example_2_test_mapping.png
  docs/images/example_3_coverage_mapping.png
  docs/images/example_3_test_mapping.png
  docs/images/example_4_coverage_mapping.png
  docs/images/example_4_test_mapping.png
  docs/userguide/coverage.md
  source/api/ut_runner.pkb
  source/core/coverage/ut_coverage.pkb
  source/core/types/ut_object_name.tpb
  source/core/types/ut_run.tpb
  source/core/types/ut_run.tps
  source/core/ut_file_mapper.pkb
  source/core/ut_file_mapper.pks
  source/core/ut_suite_manager.pkb
  source/core/ut_suite_manager.pks
  test/core/annotations/test_annot_throws_exception.pkb
  test/core/annotations/test_annot_throws_exception.pks
  test/core/reporters/test_coverage.pkb
  test/core/reporters/test_coverage.pks
  test/core/test_file_mapper.pkb
  test/core/test_file_mapper.pks
  test/install_tests.sql
Labels: in progress

#641 Fixes to new asso array during mock coverage id.
  source/core/coverage/ut_coverage_helper.pkb
  source/core/coverage/ut_coverage_helper.pks
  test/core/reporters/test_block_coverage.pkb
  test/core/reporters/test_coverage.pkb
Labels: in progress

#644 Feature/12ccoverage doc
  docs/images/extended_coverage_html_line.png
  docs/images/extended_coverage_html_summary.png
  docs/userguide/coverage.md
Labels: documentation, in progress

#646 Fixed issue with implicit cursor
  source/core/ut_utils.pkb
  source/core/ut_utils.pks
  source/expectations/data_values/ut_compound_data_helper.pkb
  source/expectations/data_values/ut_data_value_refcursor.tpb
  test/core/expectations/compound_data/test_expectations_cursor.pkb
  test/core/expectations/compound_data/test_expectations_cursor.pks
Labels: in progress

#647 update test name
  test/core/expectations/compound_data/test_expectations_cursor.pkb
  test/core/expectations/compound_data/test_expectations_cursor.pks
Labels: in progress

#652 Feature/fix output buffer timeout
  .travis.yml
  VERSION
  source/core/output_buffers/ut_output_table_buffer.tpb
Labels: bugfix, in progress

#653 Feature/fix block coverage
  docs/userguide/coverage.md
  examples/RunExpectations.sql
  old_tests/RunAll.sql
  source/core/coverage/ut_coverage.pkb
  source/core/coverage/ut_coverage.pks
  source/core/coverage/ut_coverage_block.pkb
  source/core/coverage/ut_coverage_block.pks
  source/core/coverage/ut_coverage_helper.pkb
  source/core/coverage/ut_coverage_helper.pks
  source/core/coverage/ut_coverage_helper_block.pkb
  source/core/coverage/ut_coverage_helper_block.pks
  source/core/coverage/ut_coverage_helper_profiler.pkb
  source/core/coverage/ut_coverage_helper_profiler.pks
  source/core/coverage/ut_coverage_profiler.pkb
  source/core/coverage/ut_coverage_profiler.pks
  source/core/events/ut_event_listener.tps
  source/create_synonyms_and_grants_for_public.sql
  source/create_synonyms_and_grants_for_user.sql
  test/core.pkb
  test/core/reporters/test_coverage.pkb
  test/core/reporters/test_extended_coverage.pkb
Labels: bugfix, in progress

#655 releasing v3.1.1
  .travis.yml
  VERSION
  docs/userguide/coverage.md
  examples/RunExpectations.sql
  old_tests/RunAll.sql
  sonar-project.properties
  source/core/coverage/ut_coverage.pkb
  source/core/coverage/ut_coverage.pks
  source/core/coverage/ut_coverage_block.pkb
  source/core/coverage/ut_coverage_block.pks
  source/core/coverage/ut_coverage_helper.pkb
  source/core/coverage/ut_coverage_helper.pks
  source/core/coverage/ut_coverage_helper_block.pkb
  source/core/coverage/ut_coverage_helper_block.pks
  source/core/coverage/ut_coverage_helper_profiler.pkb
  source/core/coverage/ut_coverage_helper_profiler.pks
  source/core/coverage/ut_coverage_profiler.pkb
  source/core/coverage/ut_coverage_profiler.pks
  source/core/events/ut_event_listener.tps
  source/core/output_buffers/ut_output_table_buffer.tpb
  source/core/ut_utils.pks
  source/create_synonyms_and_grants_for_public.sql
  source/create_synonyms_and_grants_for_user.sql
  test/core.pkb
  test/core/reporters/test_coverage.pkb
  test/core/reporters/test_extended_coverage.pkb
Labels: in progress
