Repository utPLSQL/utPLSQL, pull requests merged in 2018-05, with the labels that each got.

#661 Fixed installation order to eliminate compilation error warning
  source/expectations/data_values/ut_compound_data_value.tpb
  source/install.sql
  source/uninstall.sql
Labels: bugfix, in progress

#660 Bugfix/non sysdba install
  docs/userguide/install.md
  source/core/ut_dbms_output_cache.sql
  source/create_user_grants.sql
  source/create_user_synonyms.sql
  source/uninstall.sql
Labels: in progress

#686 Bugfix/dbms output capture before run
  source/core/ut_utils.pkb
  test/api/test_ut_runner.pkb
Labels: bugfix
