Repository utPLSQL/utPLSQL, pull requests merged in 2019-03, with the labels that each got.

#846 Fixed annotations on CANADIAN FRENCH NLS settings
  source/core/annotations/ut_annotation_parser.pkb
  test/core/annotations/test_annotation_parser.pkb
  test/core/annotations/test_annotation_parser.pks
Labels: bugfix

#847 `ut_output_table_buffer` will now throw an exception on timeout.
  examples/developer_examples/RunExampleTestSuiteWithCompositeReporter.sql
  examples/developer_examples/RunExampleTestSuiteWithCustomReporter.sql
  source/api/ut_runner.pkb
  source/core/events/ut_event_manager.pkb
  source/core/events/ut_event_manager.pks
  source/core/output_buffers/ut_output_buffer_tmp.sql
  source/core/output_buffers/ut_output_table_buffer.tpb
  source/core/types/ut_logical_suite.tpb
  source/core/types/ut_output_reporter_base.tpb
  source/core/types/ut_output_reporter_base.tps
  source/core/types/ut_reporter_base.tpb
  source/core/types/ut_reporter_base.tps
  source/core/types/ut_run.tpb
  source/core/types/ut_suite.tpb
  source/core/types/ut_test.tpb
  source/core/ut_suite_builder.pkb
  source/core/ut_utils.pks
  test/core/reporters/test_realtime_reporter.pkb
  test/core/test_output_buffer.pkb
Labels: enhancement

#852 Savepoints are working properly on distributed transactions.
  source/core/types/ut_suite_item.tpb
  test/api/test_ut_run.pkb
  test/api/test_ut_run.pks
Labels: bugfix

#858 Modify a code to fail when inserting a suitepath over 1k long.
  source/core/types/ut_suite_item.tps
  source/core/ut_suite_manager.pkb
  source/core/ut_utils.pkb
  source/core/ut_utils.pks
  test/core/test_suite_manager.pkb
  test/core/test_suite_manager.pks
Labels: bug

#860 Added `ut.version` and `ut_run_info()` onto documentation.
  docs/userguide/install.md
  source/create_synonyms_and_grants_for_public.sql
  source/create_user_grants.sql
  source/create_user_synonyms.sql
Labels: enhancement

#859 Fixed example in documentation for context.
  docs/userguide/annotations.md
Labels: bugfix, documentation

#865 Fixing issue when users with min privs execute empty matcher.
  source/create_synonyms_and_grants_for_public.sql
  source/create_user_grants.sql
  source/create_user_synonyms.sql
  test/core/min_grant_user/test_min_grant_user.pkb
  test/core/min_grant_user/test_min_grant_user.pks
  test/helpers/test_dummy_object.tps
  test/helpers/test_dummy_object_list.tps
  test/helpers/ut3user#.test_cursor_grants.pkb
  test/helpers/ut3user#.test_cursor_grants.pks
Labels: bugfix
