Repository utPLSQL/utPLSQL, pull requests merged in 2019-06, with the labels that each got.

#931 Fixes #921 - Assert input params in dynamic SQL
  source/core/annotations/ut_annotation_manager.pkb
  source/core/coverage/ut_coverage.pkb
  source/core/types/ut_suite_item.tpb
  source/core/ut_metadata.pkb
  source/core/ut_suite_manager.pkb
Labels: bugfix, security

#926 Failure details in sonar test reporter are now CDATA
  source/core/types/ut_test.tpb
  source/core/types/ut_test.tps
  source/core/ut_utils.pkb
  source/core/ut_utils.pks
  source/reporters/ut_junit_reporter.tpb
  source/reporters/ut_sonar_test_reporter.tpb
  source/reporters/ut_tfs_junit_reporter.tpb
  test/ut3_user/api/test_ut_run.pkb
  test/ut3_user/reporters.pkb
  test/ut3_user/reporters.pks
  test/ut3_user/reporters/test_documentation_reporter.pkb
  test/ut3_user/reporters/test_junit_reporter.pkb
  test/ut3_user/reporters/test_junit_reporter.pks
  test/ut3_user/reporters/test_sonar_test_reporter.pkb
  test/ut3_user/reporters/test_sonar_test_reporter.pks
  test/ut3_user/reporters/test_tfs_junit_reporter.pkb
  test/ut3_user/reporters/test_tfs_junit_reporter.pks
Labels: bugfix

#923 Anydata join / exclude / include
  docs/userguide/advanced_data_comparison.md
  source/core/ut_utils.pkb
  source/core/ut_utils.pks
  source/expectations/data_values/ut_compound_data_helper.pkb
  source/expectations/data_values/ut_cursor_column.tpb
  source/expectations/data_values/ut_cursor_column.tps
  source/expectations/data_values/ut_cursor_details.tpb
  source/expectations/data_values/ut_cursor_details.tps
  source/expectations/data_values/ut_data_value_anydata.tpb
  source/expectations/data_values/ut_data_value_refcursor.tpb
  test/ut3_user/expectations/test_expectation_anydata.pkb
Labels: bugfix

#935 Fixed output_buffer purging error.
  source/core/coverage/ut_coverage_helper.pkb
  source/core/coverage/ut_coverage_sources_tmp.sql
  source/core/output_buffers/ut_output_buffer_base.tpb
  source/core/output_buffers/ut_output_buffer_base.tps
  source/core/output_buffers/ut_output_buffer_info_tmp.sql
  source/core/output_buffers/ut_output_buffer_tmp.sql
  source/core/output_buffers/ut_output_clob_buffer_tmp.sql
  source/core/output_buffers/ut_output_clob_table_buffer.tpb
  source/core/output_buffers/ut_output_clob_table_buffer.tps
  source/core/output_buffers/ut_output_table_buffer.tpb
  source/core/output_buffers/ut_output_table_buffer.tps
  source/install.sql
  source/uninstall_objects.sql
  test/ut3_tester/core/test_output_buffer.pkb
  test/ut3_tester/core/test_output_buffer.pks
Labels: bugfix

#937 Feature/add warnings to realtime reporter
  source/reporters/ut_realtime_reporter.tpb
  test/ut3_user/reporters/test_realtime_reporter.pkb
  test/ut3_user/reporters/test_realtime_reporter.pks
Labels: enhancement

#939 Removed dependency on `dbms_utility.name_resolve`.
  source/core/types/ut_executable.tpb
  source/core/types/ut_executable.tps
  source/core/ut_metadata.pkb
  source/core/ut_metadata.pks
  test/ut3_tester/core/annotations/test_before_after_annotations.pkb
  test/ut3_user/api/test_ut_run.pkb
  test/ut3_user/api/test_ut_run.pks
Labels: bugfix, enhancement

#928 Feature/json object
  docs/userguide/advanced_data_comparison.md
  docs/userguide/expectations.md
  source/api/ut.pkb
  source/api/ut.pks
  source/core/ut_suite_manager.pkb
  source/core/ut_utils.pkb
  source/create_synonyms_and_grants_for_public.sql
  source/create_user_grants.sql
  source/create_user_synonyms.sql
  source/expectations/data_values/ut_compound_data_helper.pkb
  source/expectations/data_values/ut_compound_data_helper.pks
  source/expectations/data_values/ut_data_value_json.tpb
  source/expectations/data_values/ut_data_value_json.tps
  source/expectations/data_values/ut_json_data_diff_tmp.sql
  source/expectations/data_values/ut_json_leaf.tpb
  source/expectations/data_values/ut_json_leaf.tps
  source/expectations/data_values/ut_json_leaf_tab.tps
  source/expectations/data_values/ut_json_tree_details.tpb
  source/expectations/data_values/ut_json_tree_details.tps
  source/expectations/json_objects_specs.sql
  source/expectations/matchers/ut_equal.tpb
  source/expectations/matchers/ut_equal.tps
  source/expectations/matchers/ut_have_count.tpb
  source/expectations/ut_expectation.tpb
  source/expectations/ut_expectation.tps
  source/expectations/ut_expectation_json.tpb
  source/expectations/ut_expectation_json.tps
  source/install.sql
  source/uninstall_objects.sql
  test/install_ut3_user_tests.sql
  test/ut3_user/expectations/test_expectations_json.pkb
  test/ut3_user/expectations/test_expectations_json.pks
Labels: enhancement, idea

#948 Fix issue for Oracle 11.2 where the local collection is used SQL
  source/expectations/data_values/ut_compound_data_helper.pkb
  source/expectations/data_values/ut_compound_data_helper.pks
  source/expectations/data_values/ut_data_value_json.tpb
Labels: bugfix

#949 Removed need to grant `ut_annotation_manager` to users.
  source/api/ut_runner.pkb
  source/api/ut_runner.pks
  source/core/annotations/ut_annotation_manager.pkb
  source/core/annotations/ut_annotation_manager.pks
  source/core/ut_suite_manager.pkb
  source/create_synonyms_and_grants_for_public.sql
  source/create_user_grants.sql
  test/ut3_tester/core/annotations/test_annotation_manager.pkb
  test/ut3_tester_helper/main_helper.pkb
Labels: enhancement

#950 Reorganized test-users privileges
  .travis/install.sh
  source/create_utplsql_owner.sql
  source/install_ddl_trigger.sql
  source/install_headless_with_trigger.sql
  source/uninstall_objects.sql
  test/grant_ut3_owner_to_ut3_tester.sql
  test/install_and_run_tests.sh
  test/install_tests.sh
  test/run_tests.sh
Labels: enhancement

#953 Added test to confirm that long column names are suported in 3.1.7
  .travis/install.sh
  source/uninstall_objects.sql
  test/ut3_user/expectations/test_expectations_cursor.pkb
  test/ut3_user/expectations/test_expectations_cursor.pks
Labels: enhancement
