Repository utPLSQL/utPLSQL, pull requests merged in 2019-07, with the labels that each got.

#962 fixes #961 - separate warnings and errors with two linefeeds
  source/reporters/ut_realtime_reporter.tpb
Labels: enhancement

#964 Added `package` to annotation warnings.
  source/core/ut_suite_builder.pkb
  test/ut3_tester/core/test_suite_builder.pkb
Labels: enhancement

#978 Fixed issue with get_Cached_suite_rows syntax.
  source/core/ut_suite_cache_manager.pkb
  test/ut3_tester_helper/run_helper.pkb
  test/ut3_user/api/test_ut_runner.pkb
Labels: bugfix

#981 Feature/improve coverage source query
  source/core/coverage/ut_coverage.pkb
  source/core/coverage/ut_coverage.pks
  source/core/coverage/ut_coverage_helper_profiler.pkb
Labels: bugfix, enhancement
